#!/bin/bash

# depends: nerd-fonts

CONFIG_SRC_DIR=~/Documents/configuration/src
RANGER_RECIPE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

shef brew ranger w3m
shef brew w3m
shef apt w3m-img

if [ ! -d $CONFIG_SRC_DIR/.ranger-config ]; then
    git clone https://github.com/CaptainQuirk/.ranger $CONFIG_SRC_DIR/.ranger-config
    ln -s $CONFIG_SRC_DIR/.ranger-config ~/.config/ranger
fi

cd $CONFIG_SRC_DIR/.ranger-config || exit 1
git pull
cd - || exit 2

sudo cp --update "$RANGER_RECIPE_DIR/files/x-ranger" /usr/local/bin

cp --update "$RANGER_RECIPE_DIR/files/ranger.desktop" "$HOME/.local/share/applications"
cp --update "$RANGER_RECIPE_DIR/files/ranger.png" "$HOME/.local/share/icons"

grep -nri "inode" "$HOME/.local/share/applications/mimeapps.list" > /dev/null 2>&1
if [ $? -eq 1 ]; then
    echo "inode/directory=x-ranger.desktop" >> "$HOME/.local/share/applications/mimeapps.list"
fi


shef apt zenity
shef apt highlight
shef apt xpdf
shef brew atool
